<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Welcome book: translations, visual style, visit counters (no visitor data); expenses: imported platform statements (dedup). */
final class Version20260928220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Welcome book translations/style/visits, expense import source + external id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE welcome_book_visit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link VARCHAR(8) NOT NULL, booking_id BIGINT NOT NULL, day DATE NOT NULL, count INT NOT NULL, book_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX welcome_book_visit_unique ON welcome_book_visit (book_id, link, booking_id, day)');
        $this->addSql('CREATE INDEX IDX_6321BC0516A2B381 ON welcome_book_visit (book_id)');
        $this->addSql('ALTER TABLE welcome_book_visit ADD CONSTRAINT FK_6321BC0516A2B381 FOREIGN KEY (book_id) REFERENCES welcome_book (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD source VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE expense ADD external_id VARCHAR(200) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX expense_import_unique ON expense (property_id, source, external_id)');
        // Existing books get empty translations and the default style, then the default is dropped (as mapped)
        $this->addSql("ALTER TABLE welcome_book ADD translations JSON DEFAULT '{}' NOT NULL");
        $this->addSql("ALTER TABLE welcome_book ADD style JSON DEFAULT '{}' NOT NULL");
        $this->addSql('ALTER TABLE welcome_book ALTER translations DROP DEFAULT');
        $this->addSql('ALTER TABLE welcome_book ALTER style DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE welcome_book_visit DROP CONSTRAINT FK_6321BC0516A2B381');
        $this->addSql('DROP TABLE welcome_book_visit');
        $this->addSql('DROP INDEX expense_import_unique');
        $this->addSql('ALTER TABLE expense DROP source');
        $this->addSql('ALTER TABLE expense DROP external_id');
        $this->addSql('ALTER TABLE welcome_book DROP translations');
        $this->addSql('ALTER TABLE welcome_book DROP style');
    }
}
